---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephobjectstores.ceph.rook.io
spec:
  group: ceph.rook.io
  names:
    kind: CephObjectStore
    listKind: CephObjectStoreList
    plural: cephobjectstores
    singular: cephobjectstore
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            dataPool:
              properties:
                erasureCoded:
                  properties:
                    codingChunks:
                      type: integer
                    dataChunks:
                      type: integer
                failureDomain:
                  type: string
                replicated:
                  properties:
                    size:
                      type: integer
            gateway:
              properties:
                annotations: {}
                instances:
                  type: integer
                placement: {}
                port:
                  maximum: 65535
                  minimum: 1
                  type: integer
                resources: {}
                securePort: {}
                sslCertificateRef: {}
                type:
                  type: string
            metadataPool:
              properties:
                erasureCoded:
                  properties:
                    codingChunks:
                      type: integer
                    dataChunks:
                      type: integer
                failureDomain:
                  type: string
                replicated:
                  properties:
                    size:
                      type: integer
            preservePoolsOnDelete:
              type: boolean
  version: v1
