---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephfilesystems.ceph.rook.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.metadataServer.activeCount
    description: Number of desired active MDS daemons
    name: ActiveMDS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: ceph.rook.io
  names:
    kind: CephFilesystem
    listKind: CephFilesystemList
    plural: cephfilesystems
    singular: cephfilesystem
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            dataPools:
              items:
                properties:
                  erasureCoded:
                    properties:
                      codingChunks:
                        type: integer
                      dataChunks:
                        type: integer
                  failureDomain:
                    type: string
                  replicated:
                    properties:
                      size:
                        maximum: 10
                        minimum: 1
                        type: integer
              type: array
            metadataPool:
              properties:
                erasureCoded:
                  properties:
                    codingChunks:
                      type: integer
                    dataChunks:
                      type: integer
                failureDomain:
                  type: string
                replicated:
                  properties:
                    size:
                      maximum: 10
                      minimum: 1
                      type: integer
            metadataServer:
              properties:
                activeCount:
                  maximum: 10
                  minimum: 1
                  type: integer
                activeStandby:
                  type: boolean
                annotations: {}
                placement: {}
                resources: {}
            preservePoolsOnDelete:
              type: boolean
  version: v1
